In [11]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [12]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.6914349  0.28403488 0.04767229 0.79506304 0.22721454]
 [0.96464686 0.34656614 0.02829875 0.11527242 0.43096111]
 [0.38134756 0.52728326 0.47051418 0.52668657 0.64533941]
 [0.22033774 0.29989817 0.41699305 0.56006916 0.63110271]
 [0.25249293 0.84167567 0.16652813 0.99574844 0.42793432]]

[[-2.14214164e+00  1.03298696e+00 -6.76349023e-01 -5.00917244e-01
  -2.29928002e+00]
 [-2.66488283e-01  7.84327972e-01 -1.56785057e-01 -1.59617057e+00
  -1.73376459e+00]
 [-1.93573891e+00 -1.40537826e+00  1.51997998e-01  1.82225325e+00
  -1.38727999e+00]
 [-9.78337913e-01  8.90743245e-01  7.74350468e-01  1.59649184e+00
  -4.95004352e-01]
 [-6.82219352e-01  1.02444190e+00  4.65953443e-01  1.56236966e-01
  -5.03992958e-01]
 [-2.05069582e+00 -1.68181010e-01 -1.39701699e+00  2.63005488e-01
   1.91189064e+00]
 [ 7.78812530e-02  6.53430686e-01 -5.93441673e-01 -1.04038946e+00
  -8.49868280e-01]
 [ 1.88846756e+00  6.03096970e-01 -5.96698748e-01 -6.48628274e-02
  -6.89649147e-01]
 [ 2.20618728e-01  1.5507028

In [3]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

In [4]:
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 1.15923314  0.23746138 -0.08569279  1.38960624  0.850678    0.78549179
 -0.3389521  -0.44256761  0.75026777  0.11397131 -1.31483058 -1.31324139
  0.02645342 -0.48639205 -0.84068126]
[ True  True False  True  True  True False False  True  True False False
  True False False]
[1.15923314 0.23746138 1.38960624 0.850678   0.78549179 0.75026777
 0.11397131 0.02645342]


In [13]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-2.14214164e+00  1.03298696e+00 -6.76349023e-01 -5.00917244e-01
  -2.29928002e+00]
 [-2.66488283e-01  7.84327972e-01 -1.56785057e-01 -1.59617057e+00
  -1.73376459e+00]
 [-1.93573891e+00 -1.40537826e+00  1.51997998e-01  1.82225325e+00
  -1.38727999e+00]
 [-9.78337913e-01  8.90743245e-01  7.74350468e-01  1.59649184e+00
  -4.95004352e-01]
 [-6.82219352e-01  1.02444190e+00  4.65953443e-01  1.56236966e-01
  -5.03992958e-01]
 [-2.05069582e+00 -1.68181010e-01 -1.39701699e+00  2.63005488e-01
   1.91189064e+00]
 [ 7.78812530e-02  6.53430686e-01 -5.93441673e-01 -1.04038946e+00
  -8.49868280e-01]
 [ 1.88846756e+00  6.03096970e-01 -5.96698748e-01 -6.48628274e-02
  -6.89649147e-01]
 [ 2.20618728e-01  1.55070284e-01 -4.90105728e-01  9.56023741e-02
  -5.51475499e-01]
 [-1.44449805e-01  1.15183484e+00 -1.23615141e-03  5.24845051e-01
  -7.32228327e-01]]
[1.03298696 0.78432797 0.151998   1.82225325 0.89074324 0.77435047
 1.59649184 1.0244419  0.46595344 0.15623697 0.26300549 1.91189064
 0.07788125 0.6

In [14]:
print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-5.          0.23746138 -0.08569279 -5.         -5.         -5.
 -0.3389521  -0.44256761 -5.          0.11397131 -1.31483058 -1.31324139
  0.02645342 -0.48639205 -0.84068126]

[-5.          0.23746138 -0.08569279 -5.         -5.         -5.
 -0.3389521  -0.44256761 -5.          0.11397131 -1.31483058 -1.31324139
  0.02645342 -0.48639205 -0.84068126]


In [15]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)

In [16]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [17]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

In [18]:
print(loaded_vec)
print('')
print(loaded_zip)

[[-2.14214164e+00  1.03298696e+00 -6.76349023e-01 -5.00917244e-01
  -2.29928002e+00]
 [-2.66488283e-01  7.84327972e-01 -1.56785057e-01 -1.59617057e+00
  -1.73376459e+00]
 [-1.93573891e+00 -1.40537826e+00  1.51997998e-01  1.82225325e+00
  -1.38727999e+00]
 [-9.78337913e-01  8.90743245e-01  7.74350468e-01  1.59649184e+00
  -4.95004352e-01]
 [-6.82219352e-01  1.02444190e+00  4.65953443e-01  1.56236966e-01
  -5.03992958e-01]
 [-2.05069582e+00 -1.68181010e-01 -1.39701699e+00  2.63005488e-01
   1.91189064e+00]
 [ 7.78812530e-02  6.53430686e-01 -5.93441673e-01 -1.04038946e+00
  -8.49868280e-01]
 [ 1.88846756e+00  6.03096970e-01 -5.96698748e-01 -6.48628274e-02
  -6.89649147e-01]
 [ 2.20618728e-01  1.55070284e-01 -4.90105728e-01  9.56023741e-02
  -5.51475499e-01]
 [-1.44449805e-01  1.15183484e+00 -1.23615141e-03  5.24845051e-01
  -7.32228327e-01]]



In [19]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[0.6914349  0.28403488 0.04767229 0.79506304 0.22721454]
 [0.96464686 0.34656614 0.02829875 0.11527242 0.43096111]
 [0.38134756 0.52728326 0.47051418 0.52668657 0.64533941]
 [0.22033774 0.29989817 0.41699305 0.56006916 0.63110271]
 [0.25249293 0.84167567 0.16652813 0.99574844 0.42793432]]

[[-2.14214164e+00  1.03298696e+00 -6.76349023e-01 -5.00917244e-01
  -2.29928002e+00]
 [-2.66488283e-01  7.84327972e-01 -1.56785057e-01 -1.59617057e+00
  -1.73376459e+00]
 [-1.93573891e+00 -1.40537826e+00  1.51997998e-01  1.82225325e+00
  -1.38727999e+00]
 [-9.78337913e-01  8.90743245e-01  7.74350468e-01  1.59649184e+00
  -4.95004352e-01]
 [-6.82219352e-01  1.02444190e+00  4.65953443e-01  1.56236966e-01
  -5.03992958e-01]
 [-2.05069582e+00 -1.68181010e-01 -1.39701699e+00  2.63005488e-01
   1.91189064e+00]
 [ 7.78812530e-02  6.53430686e-01 -5.93441673e-01 -1.04038946e+00
  -8.49868280e-01]
 [ 1.88846756e+00  6.03096970e-01 -5.96698748e-01 -6.48628274e-02
  -6.89649147e-01]
 [ 2.20618728e-01  1.5507028

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)